package net.domain;
// Generated Nov 13, 2014 7:42:14 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * JobRating generated by hbm2java
 */
@Entity
@Table(name = "job_rating", catalog = "jobDatabase", uniqueConstraints = @UniqueConstraint(columnNames = {
		"job_id", "rating_type_id" }))
public class JobRating implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4904957482824535886L;
	private Integer id;
	private RatingType ratingType;
	private Job job;
	private int ratingNum;
	private int ratingSum;

	public JobRating() {
	}

	public JobRating(RatingType ratingType, Job job, int ratingNum,
			int ratingSum) {
		this.ratingType = ratingType;
		this.job = job;
		this.ratingNum = ratingNum;
		this.ratingSum = ratingSum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rating_type_id", nullable = false)
//	@JsonBackReference
	@JsonManagedReference
	public RatingType getRatingType() {
		return this.ratingType;
	}

	public void setRatingType(RatingType ratingType) {
		this.ratingType = ratingType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_id", nullable = false)
	@JsonBackReference
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Column(name = "rating_num", nullable = false)
	public int getRatingNum() {
		return this.ratingNum;
	}

	public void setRatingNum(int ratingNum) {
		this.ratingNum = ratingNum;
	}

	@Column(name = "rating_sum", nullable = false)
	public int getRatingSum() {
		return this.ratingSum;
	}

	public void setRatingSum(int ratingSum) {
		this.ratingSum = ratingSum;
	}

}
