package net.domain;
// Generated Nov 13, 2014 7:42:14 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * RatingType generated by hbm2java
 */
@Entity
@Table(name = "rating_type", catalog = "jobDatabase")
public class RatingType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8433224048038626050L;
	private Integer id;
	private String ratingName;
	private String description;
	private Set<JobRating> jobRatings = new HashSet<JobRating>(0);

	public RatingType() {
	}

	public RatingType(Integer id, String ratingName, String description) {
		this.id = id;
		this.ratingName = ratingName;
		this.description = description;
	}

	public RatingType(Integer id, String ratingName, String description,
			Set<JobRating> jobRatings) {
		this.id = id;
		this.ratingName = ratingName;
		this.description = description;
		this.jobRatings = jobRatings;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "rating_name", nullable = false, length = 20)
	public String getRatingName() {
		return this.ratingName;
	}

	public void setRatingName(String ratingName) {
		this.ratingName = ratingName;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ratingType")
//	@JsonManagedReference
	@JsonBackReference
	public Set<JobRating> getJobRatings() {
		return this.jobRatings;
	}

	public void setJobRatings(Set<JobRating> jobRatings) {
		this.jobRatings = jobRatings;
	}

}
